### ISSUE TITLE
Cyber elves

### ISSUE THREAD

**Issue by Appendko** [Ajarmar/platinum#1]
If I activate a cycle-elf in a stage (such as the one make every enemies drops items), and then skip a cutscene, then the effect of elf will disappear.

**Comment by Ajarmar** [comment]
Thanks for pointing this out, I've had others report this too. I'll be looking into it

**Comment by Ajarmar** [comment]
Fixed by cd05064bd564787cdc43727e99f7d951278cc7b3 / 9b70aba7534244f90690ed06ef2908331fad514a / d3958ef46b0402a7404be29da06495e9a2a2b314 (finally)
